import { Method, z } from 'mppx'

/**
 * Solana charge method — shared schema used by both server and client.
 *
 * Supports two credential payload types:
 *
 * - **type="transaction"** (default): Client signs the transaction and sends
 *   the serialized bytes to the server. The server broadcasts it to the
 *   Solana network, confirms, and verifies the transfer on-chain.
 *
 * - **type="signature"**: Client broadcasts the transaction itself and sends
 *   the confirmed transaction signature. The server verifies on-chain only.
 */
export const charge = Method.from({
  intent: 'charge',
  name: 'solana',
  schema: {
    credential: {
      payload: z.object({
        /** Payload type: "transaction" (server broadcasts) or "signature" (client already broadcast). */
        type: z.string(),
        /** Base64-encoded serialized signed transaction (when type="transaction"). */
        transaction: z.optional(z.string()),
        /** Base58-encoded transaction signature (when type="signature"). */
        signature: z.optional(z.string()),
      }),
    },
    request: z.object({
      /** Amount in smallest unit (lamports for SOL, base units for SPL tokens). */
      amount: z.string(),
      /** Identifies the unit for amount. "SOL" for native, or token symbol/mint (e.g. "USDC"). */
      currency: z.string(),
      /** Base58-encoded recipient public key. */
      recipient: z.string(),
      /** Human-readable memo describing the resource or service being paid for. */
      description: z.optional(z.string()),
      /** Merchant's reference (e.g., order ID, invoice number) for reconciliation. */
      externalId: z.optional(z.string()),
      methodDetails: z.object({
        /** Solana network: mainnet-beta, devnet, or localnet. */
        network: z.optional(z.string()),
        /** SPL token mint address. If absent, payment is in native SOL. */
        splToken: z.optional(z.string()),
        /** Token decimals (required for SPL token transfers). */
        decimals: z.optional(z.number()),
        /** Token program address (TOKEN_PROGRAM or TOKEN_2022_PROGRAM). Defaults to TOKEN_PROGRAM. */
        tokenProgram: z.optional(z.string()),
        /** Unique reference ID for this charge (server-generated, used for tracking). */
        reference: z.string(),
        /** If true, server pays transaction fees. Client must use the server's feePayerKey. */
        feePayer: z.optional(z.boolean()),
        /** Server's base58-encoded public key for fee payment. Present when feePayer is true. */
        feePayerKey: z.optional(z.string()),
        /** Server-provided base58-encoded recent blockhash. Saves the client an RPC round-trip. */
        recentBlockhash: z.optional(z.string()),
      }),
    }),
  },
})

/**
 * Solana session method shared schema used by both server and client.
 *
 * Supports four credential actions:
 *
 * - **open**: opens a payment channel, records deposit, and anchors setup tx.
 * - **update**: submits a new monotonic voucher for cumulative usage.
 * - **topup**: increases channel escrow using a separate topup transaction.
 * - **close**: final voucher update used to finalize channel settlement.
 */
export const session = Method.from({
  intent: 'session',
  name: 'solana',
  schema: {
    credential: {
      payload: z.discriminatedUnion('action', [
        z.object({
          /** Session lifecycle action. */
          action: z.literal('open'),
          /** Unique channel identifier generated by the client authorizer. */
          channelId: z.string(),
          /** Wallet payer for this channel (base58 public key). */
          payer: z.string(),
          /** Authorization mode selected by the authorizer implementation. */
          authorizationMode: z.string(),
          /** Initial escrow amount committed for this channel. */
          depositAmount: z.string(),
          /** On-chain transaction reference proving open/setup step. */
          openTx: z.string(),
          /** Optional voucher expiration timestamp in ISO-8601 format. */
          expiresAt: z.optional(z.string()),
          /** Optional advertised authorizer capabilities for client hints. */
          capabilities: z.optional(
            z.object({
              /** Maximum cumulative authorized amount for this channel. */
              maxCumulativeAmount: z.optional(z.string()),
              /** Allowed action subset advertised by the authorizer. */
              allowedActions: z.optional(z.array(z.string())),
            }),
          ),
          /** Signed session voucher payload for open action. */
          voucher: z.object({
            voucher: z.object({
              /** Channel identifier bound to this voucher. */
              channelId: z.string(),
              /** Wallet payer bound to this voucher. */
              payer: z.string(),
              /** Channel recipient service wallet. */
              recipient: z.string(),
              /** Monotonic cumulative authorized amount. */
              cumulativeAmount: z.string(),
              /** Monotonic sequence number for replay protection. */
              sequence: z.number(),
              /** Meter name for priced usage tracking. */
              meter: z.string(),
              /** Meter units associated with this authorization update. */
              units: z.string(),
              /** Optional voucher expiration timestamp in ISO-8601 format. */
              expiresAt: z.optional(z.string()),
              /** Server-provided nonce for challenge binding. */
              serverNonce: z.string(),
              /** Chain identifier, for example `solana:mainnet-beta`. */
              chainId: z.string(),
              /** Channel program address expected by server verifier. */
              channelProgram: z.string(),
            }),
            /** Voucher signer public key. */
            signer: z.string(),
            /** Base58/encoded signature over canonical voucher bytes. */
            signature: z.string(),
            /** Signature scheme discriminator (`ed25519` or `swig-session`). */
            signatureType: z.string(),
          }),
        }),
        z.object({
          /** Session lifecycle action. */
          action: z.literal('update'),
          /** Existing channel identifier targeted by this update. */
          channelId: z.string(),
          /** Signed session voucher payload for usage update. */
          voucher: z.object({
            voucher: z.object({
              channelId: z.string(),
              payer: z.string(),
              recipient: z.string(),
              cumulativeAmount: z.string(),
              sequence: z.number(),
              meter: z.string(),
              units: z.string(),
              expiresAt: z.optional(z.string()),
              serverNonce: z.string(),
              chainId: z.string(),
              channelProgram: z.string(),
            }),
            signer: z.string(),
            signature: z.string(),
            signatureType: z.string(),
          }),
        }),
        z.object({
          /** Session lifecycle action. */
          action: z.literal('topup'),
          /** Existing channel identifier targeted by this topup. */
          channelId: z.string(),
          /** Additional escrow amount to add to channel deposit. */
          additionalAmount: z.string(),
          /** On-chain transaction reference proving topup execution. */
          topupTx: z.string(),
        }),
        z.object({
          /** Session lifecycle action. */
          action: z.literal('close'),
          /** Existing channel identifier targeted by this close. */
          channelId: z.string(),
          /** Optional on-chain settlement transaction reference for this close. */
          closeTx: z.optional(z.string()),
          /** Signed final voucher payload for close action. */
          voucher: z.object({
            voucher: z.object({
              channelId: z.string(),
              payer: z.string(),
              recipient: z.string(),
              cumulativeAmount: z.string(),
              sequence: z.number(),
              meter: z.string(),
              units: z.string(),
              expiresAt: z.optional(z.string()),
              serverNonce: z.string(),
              chainId: z.string(),
              channelProgram: z.string(),
            }),
            signer: z.string(),
            signature: z.string(),
            signatureType: z.string(),
          }),
        }),
      ]),
    },
    request: z.object({
      /** Service recipient wallet that receives settlement funds. */
      recipient: z.string(),
      /** Solana network name, for example mainnet-beta, devnet, localnet. */
      network: z.optional(z.string()),
      asset: z.object({
        /** Asset kind: native SOL or SPL token. */
        kind: z.string(),
        /** SPL mint address when kind is `spl`. */
        mint: z.optional(z.string()),
        /** Token decimals for amount normalization. */
        decimals: z.number(),
        /** Optional ticker/symbol used for display. */
        symbol: z.optional(z.string()),
      }),
      /** Channel program address used to verify vouchers and actions. */
      channelProgram: z.string(),
      /** Optional pricing contract used to derive debit increments. */
      pricing: z.optional(
        z.object({
          /** Logical unit name charged by the service. */
          unit: z.string(),
          /** Price per unit in asset base units. */
          amountPerUnit: z.string(),
          /** Meter identifier for usage accounting. */
          meter: z.string(),
          /** Optional minimum debit to apply per request. */
          minDebit: z.optional(z.string()),
        }),
      ),
      /** Optional server hints for default session behavior. */
      sessionDefaults: z.optional(
        z.object({
          /** Suggested channel deposit to use on auto-open. */
          suggestedDeposit: z.optional(z.string()),
          /** Suggested time-to-live for channel/session in seconds. */
          ttlSeconds: z.optional(z.number()),
          /** Optional settlement cadence policy hints. */
          settleInterval: z.optional(
            z.object({
              kind: z.string(),
              minIncrement: z.optional(z.string()),
              seconds: z.optional(z.number()),
            }),
          ),
          /** Optional close behavior hint for client UX. */
          closeBehavior: z.optional(z.string()),
        }),
      ),
      /** Optional server-side verifier policy hints. */
      verifier: z.optional(
        z.object({
          /** Supported authorization modes for this endpoint. */
          acceptAuthorizationModes: z.optional(z.array(z.string())),
          /** Maximum allowable client/server clock skew in seconds. */
          maxClockSkewSeconds: z.optional(z.number()),
        }),
      ),
    }),
  },
})
